[project]
name = "pyclad"
version = "0.1.0"
description = "pyclad modified with reservoir sampling"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets",
    "numpy",
    "pandas",
    "pyod",
    "seaborn",
]
